# Generated by Django 4.1.7 on 2023-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="taggeditem",
            options={"ordering": ["-created"]},
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["slug"], name="assets_imag_slug_da6b63_idx"),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["-created"], name="assets_imag_created_da0dfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="assets_tag_slug_b16dc4_idx"),
        ),
        migrations.AddIndex(
            model_name="taggeditem",
            index=models.Index(
                fields=["-created"], name="assets_tagg_created_7584d0_idx"
            ),
        ),
    ]
