# Generated by Django 4.1.7 on 2023-07-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="assets.image"
            ),
        ),
    ]
