# Generated by Django 4.1.7 on 2023-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_image_options_alter_taggeditem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="source",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
