# Generated by Django 4.1.7 on 2023-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_image_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
